version: '3.7'

services:
  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:16.3
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    depends_on: [app_db]
    container_name: app
    image: app
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        /app/scripts/makemigration.sh &&
        /app/scripts/migrate.sh &&
        /app/scripts/start.sh
      "
volumes:
  app_db_data:
    driver: "local"
