"""

Revision ID: 665485b4ce84
Revises:
Create Date: 2025-03-30 14:35:59.222388

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '665485b4ce84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    )
    op.create_table(
        'user_audio_files',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_audio_files_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('user_audio_files_pkey')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_audio_files')
    op.drop_table('users')
    # ### end Alembic commands ###
