name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/ruff:0.11.2-alpine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Ruff Version
        run: ruff --version

      - name: Run Ruff Check
        run: ruff check --output-format=gitlab > code-quality-report.json

      - name: Upload Code Quality Report
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-report
          path: code-quality-report.json
